### PR TITLE
adding changelog to the repo

### LINKED ISSUE #34: add changelog
This adapter could use a changelog to indicate what changed in the various releases.

### PR DESCRIPTION
**Pull request by rlgomes**
fixes #34

### CODE REVIEW

**Comment by rlgomes** [comment]
@demmer

**Comment by demmer** [comment]
What about releases before 0.4.0? I think there should be entries for them as well, even if they're brief.

**Comment by rlgomes** [comment]
@demmer sure, I just didn't want to try and piece together the history but it shoudn't be to bad.

**Comment by rlgomes** [comment]
@demmer thats as far as I think we need to go back.

**Comment by demmer** [comment]
Looks good

**Pull request merged**
